version: '3.8'

services:
  avito-proj:
    build: ./
    command: ./avito-proj
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=MySuperPassword

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=MySuperPassword
      - POSTGRES_USER=my_user
    ports:
      - 5436:5432